permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 步步高教育电子小学家教机产品线团队技术博客
  email: zmywly8866@gmail.com

# 站点信息
title: 步步高教育电子小学家教机产品线团队技术博客 
description: 步步高教育电子小学家教机产品线团队技术博客
url: http://bbkopen.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico