permalink: /:year/:month/:day/:title.html
paginate: 50
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 步步高教育电子小学家教机产品线团队技术博客
  email: zmywly8866@gmail.com

# 站点信息
title: 步步高教育电子小学家教机产品线团队技术博客 
description: 步步高教育电子小学家教机产品线团队技术博客
url: http://openappteam.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://img.my.csdn.net/uploads/201511/04/1446612875_6317.png
favicon: http://img.my.csdn.net/uploads/201511/04/1446612875_6317.png

# disqus 设置
disqus:
  shortname: bbkopen

# 主题设置，自动激活某个标签
active: 技术

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录